### PR TITLE
Fix interrupt handling issues in csp: ensure first node is stopped and reset signaled flag across runs

### LINKED ISSUE #147: The first node in a graph does not stop() properly on an interrupt
**Describe the bug**

If you have a graph and stop execution with an interrupt, the first node in the graph's stop() logic will not be invoked, but all others nodes will. If an exception is raised, on the other hand, all nodes stop() logic will be invoked.

**To Reproduce**

```python
import csp
import traceback
from csp.impl.error_handling import set_print_full_exception_stack
from csp import ts
import time

@csp.node
def foo(x: ts[int]):
    with csp.start():
        print("foo start")
    
    with csp.stop():
        print("foo stop")

    #raise

@csp.node
def bar():
    with csp.start():
        print("bar start")

    with csp.stop():
        print("bar stop")

@csp.node
def foobar():
    with csp.start():
        print("foobar start")

    with csp.stop():
        print("foobar stop")


@csp.graph
def my_graph():
    foo(csp.const(1))
    bar()
    foobar()

def main():
    csp.run(my_graph, realtime=True)

if __name__ == '__main__':
    set_print_full_exception_stack( True )
    main()
```

If you run this and then interrupt it you get:
```
foo start
bar start
foobar start
^Cbar stop
foobar stop
```

Now let's say you reorder the nodes in the graph such that it's:
```
@csp.graph
def my_graph():
    bar()
    foo(csp.const(1))
    foobar()

```

Do the same thing, run it and then interrupt it. You get:

```
bar start
foo start
foobar start
^Cfoo stop
foobar stop
```

Pretty strange. Now let's say you uncomment the raise in foo() so that the graph fails on an exception. You get:

```
foo start
bar start
foobar start
foo stop
bar stop
foobar stop
```

**Expected behavior**

Expected behaviour would be all stop() logic is called (so the last case, which is what happens on a raise).

**Error Message**

N/a

**Runtime Environment**

[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, csp; print(csp.__version__); print(sys.version); print(sys.platform)
None
3.8.10 | packaged by conda-forge | (default, Sep 13 2021, 21:46:58) 
[GCC 9.4.0]
linux

**Additional context**

### PR DESCRIPTION
**Pull request by AdamGlustein**
Closes #147

### CODE REVIEW

File: cpp/csp/engine/RootEngine.cpp [hunk 1]
```diff
@@ -11,12 +11,12 @@
 namespace csp
 {
 
-static volatile bool    g_SIGNALED = false;
+static volatile int     g_SIGNAL_COUNT = 0;
```
Comment (robambalu) [inline cpp/csp/engine/RootEngine.cpp:14]: Can we add a comment explaining why this was made a counter

Comment (AdamGlustein) [reply cpp/csp/engine/RootEngine.cpp:14]: Done

**Review by robambalu — APPROVED** [review]
